// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: answers.sql

package db

import (
	"context"
)

const createAnswer = `-- name: CreateAnswer :one
INSERT INTO "answers" ("question", "submission", "answer") VALUES ($1, $2, $3) RETURNING "id"
`

type CreateAnswerParams struct {
	Question   int32  `json:"question"`
	Submission int32  `json:"submission"`
	Answer     string `json:"answer"`
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (int32, error) {
	row := q.queryRow(ctx, q.createAnswerStmt, createAnswer, arg.Question, arg.Submission, arg.Answer)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const test = `-- name: Test :one
SELECT 1
`

func (q *Queries) Test(ctx context.Context) (int32, error) {
	row := q.queryRow(ctx, q.testStmt, test)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
