// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: courses.sql

package db

import (
	"context"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO "courses" ("id", "code", "year") VALUES ($1, $2, $3) RETURNING id, code, year
`

type CreateCourseParams struct {
	ID   int32  `json:"id"`
	Code string `json:"code"`
	Year int32  `json:"year"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, createCourse, arg.ID, arg.Code, arg.Year)
	var i Course
	err := row.Scan(&i.ID, &i.Code, &i.Year)
	return i, err
}
