// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: courses.sql

package db

import (
	"context"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO "courses" ("code", "year") VALUES ($1, $2) RETURNING "id"
`

type CreateCourseParams struct {
	Code string `json:"code"`
	Year int32  `json:"year"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createCourse, arg.Code, arg.Year)
	var id int32
	err := row.Scan(&id)
	return id, err
}
