// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: feedback.sql

package db

import (
	"context"
)

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO "feedback" ("review", "answer", "rating", "feedback") 
    VALUES ($1, $2, $3, $4) RETURNING "id"
`

type CreateFeedbackParams struct {
	Review   int32  `json:"review"`
	Answer   int32  `json:"answer"`
	Rating   int32  `json:"rating"`
	Feedback string `json:"feedback"`
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createFeedback,
		arg.Review,
		arg.Answer,
		arg.Rating,
		arg.Feedback,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
