// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"
)

type Answer struct {
	ID         int32  `json:"id"`
	Question   int32  `json:"question"`
	Submission int32  `json:"submission"`
	Answer     string `json:"answer"`
}

type Assignment struct {
	Course  int32     `json:"course"`
	TimeDue time.Time `json:"time_due"`
}

type Course struct {
	ID   int32  `json:"id"`
	Code string `json:"code"`
	Year int32  `json:"year"`
}

type Feedback struct {
	ID       int32  `json:"id"`
	Review   int32  `json:"review"`
	Answer   int32  `json:"answer"`
	Rating   int32  `json:"rating"`
	Feedback string `json:"feedback"`
}

type Question struct {
	ID         int32  `json:"id"`
	Assignment int32  `json:"assignment"`
	Prompt     string `json:"prompt"`
	Order      int32  `json:"order"`
}

type Review struct {
	ID         int32        `json:"id"`
	Submission int32        `json:"submission"`
	ReviewerID string       `json:"reviewer_id"`
	FinishedAt sql.NullTime `json:"finished_at"`
	CreatedAt  time.Time    `json:"created_at"`
}

type Submission struct {
	ID         int32     `json:"id"`
	User       string    `json:"user"`
	Assignment int32     `json:"assignment"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
}

type UserCourseEnrollment struct {
	User   string `json:"user"`
	Course int32  `json:"course"`
}
