// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"
)

type Answer struct {
	ID         int32  `json:"id"`
	Question   int32  `json:"question"`
	Submission int32  `json:"submission"`
	Answer     string `json:"answer"`
}

type AnswersSummary struct {
	ID         int32   `json:"id"`
	Question   int32   `json:"question"`
	Submission int32   `json:"submission"`
	Answer     string  `json:"answer"`
	Count      int64   `json:"count"`
	Rating     float64 `json:"rating"`
}

type Assignment struct {
	ID                   int32     `json:"id"`
	Name                 string    `json:"name"`
	Course               int32     `json:"course"`
	ReviewsPerSubmission int32     `json:"reviews_per_submission"`
	TimeDue              time.Time `json:"time_due"`
}

type AssignmentRatingCache struct {
	AssignmentID int32           `json:"assignment_id"`
	AvgRating    sql.NullFloat64 `json:"avg_rating"`
	ExpiresAt    time.Time       `json:"expires_at"`
}

type AssignmentSummary struct {
	ID                   int32     `json:"id"`
	Name                 string    `json:"name"`
	Course               int32     `json:"course"`
	ReviewsPerSubmission int32     `json:"reviews_per_submission"`
	TimeDue              time.Time `json:"time_due"`
	Rating               float64   `json:"rating"`
}

type AssignmentWithRating struct {
	ID                   int32     `json:"id"`
	Name                 string    `json:"name"`
	Course               int32     `json:"course"`
	ReviewsPerSubmission int32     `json:"reviews_per_submission"`
	TimeDue              time.Time `json:"time_due"`
	Rating               float64   `json:"rating"`
}

type Course struct {
	ID   int32  `json:"id"`
	Code string `json:"code"`
	Year int32  `json:"year"`
}

type CourseSummary struct {
	ID        int32   `json:"id"`
	Code      string  `json:"code"`
	Year      int32   `json:"year"`
	Count     int64   `json:"count"`
	AvgRating float64 `json:"avg_rating"`
}

type Feedback struct {
	ID       int32  `json:"id"`
	Review   int32  `json:"review"`
	Answer   int32  `json:"answer"`
	Rating   int32  `json:"rating"`
	Feedback string `json:"feedback"`
}

type Question struct {
	ID         int32  `json:"id"`
	Assignment int32  `json:"assignment"`
	Prompt     string `json:"prompt"`
	Order      int32  `json:"order"`
}

type QuestionSummary struct {
	ID         int32   `json:"id"`
	Assignment int32   `json:"assignment"`
	Prompt     string  `json:"prompt"`
	Order      int32   `json:"order"`
	Count      int64   `json:"count"`
	Rating     float64 `json:"rating"`
}

type Review struct {
	ID         int32        `json:"id"`
	Submission int32        `json:"submission"`
	ReviewerID string       `json:"reviewer_id"`
	FinishedAt sql.NullTime `json:"finished_at"`
	CreatedAt  time.Time    `json:"created_at"`
}

type Submission struct {
	ID         int32     `json:"id"`
	User       string    `json:"user"`
	Assignment int32     `json:"assignment"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
}

type UserCourseEnrollment struct {
	User   string `json:"user"`
	Course int32  `json:"course"`
}
