// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	CrateQuestion(ctx context.Context, arg CrateQuestionParams) (Question, error)
	CreateAnswer(ctx context.Context, arg CreateAnswerParams) (Answer, error)
	CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserCourseEnrollment(ctx context.Context, arg CreateUserCourseEnrollmentParams) (UserCourseEnrollment, error)
	GetUser(ctx context.Context, id string) (User, error)
}

var _ Querier = (*Queries)(nil)
