// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	CreateAnswer(ctx context.Context, arg CreateAnswerParams) (int32, error)
	CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (int32, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (int32, error)
	CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (int32, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (int32, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (int32, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (int32, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateUserCourseEnrollment(ctx context.Context, arg CreateUserCourseEnrollmentParams) error
	GetAssignment(ctx context.Context, id int32) (GetAssignmentRow, error)
	GetUser(ctx context.Context, id string) (User, error)
	Test(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
