// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: questions.sql

package db

import (
	"context"
)

const crateQuestion = `-- name: CrateQuestion :one
INSERT INTO "questions" ("id", "assignment", "prompt", "order") VALUES ($1, $2, $3, $4) RETURNING id, assignment, prompt, "order"
`

type CrateQuestionParams struct {
	ID         int32  `json:"id"`
	Assignment int32  `json:"assignment"`
	Prompt     string `json:"prompt"`
	Order      int32  `json:"order"`
}

func (q *Queries) CrateQuestion(ctx context.Context, arg CrateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, crateQuestion,
		arg.ID,
		arg.Assignment,
		arg.Prompt,
		arg.Order,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Assignment,
		&i.Prompt,
		&i.Order,
	)
	return i, err
}
