// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: questions.sql

package db

import (
	"context"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO "questions" ("assignment", "prompt", "order") VALUES ($1, $2, $3) RETURNING "id"
`

type CreateQuestionParams struct {
	Assignment int32  `json:"assignment"`
	Prompt     string `json:"prompt"`
	Order      int32  `json:"order"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (int32, error) {
	row := q.queryRow(ctx, q.createQuestionStmt, createQuestion, arg.Assignment, arg.Prompt, arg.Order)
	var id int32
	err := row.Scan(&id)
	return id, err
}
