// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: reviews.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createReview = `-- name: CreateReview :one
INSERT INTO "reviews" ("submission", "reviewer_id", "finished_at", "created_at") 
    VALUES ($1, $2, $3, $4) RETURNING "id"
`

type CreateReviewParams struct {
	Submission int32        `json:"submission"`
	ReviewerID string       `json:"reviewer_id"`
	FinishedAt sql.NullTime `json:"finished_at"`
	CreatedAt  time.Time    `json:"created_at"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (int32, error) {
	row := q.queryRow(ctx, q.createReviewStmt, createReview,
		arg.Submission,
		arg.ReviewerID,
		arg.FinishedAt,
		arg.CreatedAt,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
