// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: submissions.sql

package db

import (
	"context"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO "submissions" ("user", "assignment") VALUES ($1, $2) RETURNING "id"
`

type CreateSubmissionParams struct {
	User       string `json:"user"`
	Assignment int32  `json:"assignment"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (int32, error) {
	row := q.queryRow(ctx, q.createSubmissionStmt, createSubmission, arg.User, arg.Assignment)
	var id int32
	err := row.Scan(&id)
	return id, err
}
